import { type SdkCollectionConfig } from './types'
import { mapFieldType } from './field-map'

function toPascalCase(name: string): string {
  return name
    .split(/[-_\s]+/)
    .map((w) => (w.charAt(0) ?? '').toUpperCase() + w.slice(1))
    .join('')
}

export function emitCollections(collections: SdkCollectionConfig[]): string {
  const lines: string[] = ['// AUTO-GENERATED by @sonicjs-cms/sdk codegen. Do not edit.', '']

  for (const col of collections) {
    const interfaceName = `${toPascalCase(col.name)}Data`
    const required = new Set<string>(col.schema?.required ?? [])
    const properties = col.schema?.properties ?? {}

    lines.push(`export interface ${interfaceName} {`)
    for (const [key, fieldDef] of Object.entries(properties)) {
      const isRequired = required.has(key)
      const tsType = mapFieldType(fieldDef)
      lines.push(`  ${key}${isRequired ? '' : '?'}: ${tsType}`)
    }
    lines.push('}')
    lines.push('')
  }

  lines.push('export interface Collections {')
  for (const col of collections) {
    const interfaceName = `${toPascalCase(col.name)}Data`
    lines.push(`  ${col.name}: { data: ${interfaceName} }`)
  }
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}
