/**
 * Wrangler.toml [triggers] cron codegen
 *
 * Cloudflare Workers cron triggers are deploy-time static — they must be listed
 * in `wrangler.toml` at deploy time and cannot be changed at runtime. This module
 * provides utilities to generate and validate the `[triggers]` section from the
 * plugin list, so the file stays in sync with declared plugin crons.
 *
 * Usage in a codegen script:
 *
 *   const schedules = collectCronSchedules(allPlugins)
 *   const updated = updateWranglerTriggers(tomlContent, schedules)
 *   writeFileSync('wrangler.toml', updated, 'utf8')
 *
 * Usage in a CI guard test:
 *
 *   const actual = parseCronTriggers(tomlContent)
 *   const expected = collectCronSchedules(allPlugins)
 *   expect(actual).toEqual(expected.sort())
 */

import { collectCronSchedules } from './cron'
import type { CronablePlugin } from './cron'

export { collectCronSchedules }
export type { CronablePlugin }

/**
 * Parse the cron trigger expressions from a `wrangler.toml` file.
 * Returns an array of cron strings found under `[triggers]`, sorted.
 */
export function parseCronTriggers(tomlContent: string): string[] {
  const lines = tomlContent.split('\n')
  const result: string[] = []
  let inTriggers = false

  for (const raw of lines) {
    const line = raw.trim()
    if (line === '[triggers]') { inTriggers = true; continue }
    if (inTriggers && line.startsWith('[') && line !== '[triggers]') { inTriggers = false }
    if (!inTriggers) continue
    // Match: crons = ["expr1", "expr2"] (single-line) or individual items
    const multiMatch = line.match(/^crons\s*=\s*\[(.+)\]/)
    if (multiMatch) {
      const items = multiMatch[1]!.match(/"([^"]+)"/g) ?? []
      result.push(...items.map((s) => s.replace(/"/g, '')))
    }
  }

  return result.sort()
}

/**
 * Update the `[triggers] crons` section in a wrangler.toml string.
 *
 * If the `[triggers]` section exists, replaces its `crons` line.
 * If it does not exist and schedules is non-empty, appends it.
 * If schedules is empty, removes the section entirely.
 *
 * Returns the updated toml content.
 */
export function updateWranglerTriggers(tomlContent: string, schedules: string[]): string {
  const triggersBlock = schedules.length > 0
    ? `[triggers]\ncrons = [${schedules.map((s) => `"${s}"`).join(', ')}]`
    : ''

  // Replace existing [triggers] block
  const withoutTriggers = tomlContent.replace(/\[triggers\]\n(?:.*\n)*?(?=\[|\s*$)/m, '')

  if (!triggersBlock) return withoutTriggers.trimEnd() + '\n'
  return withoutTriggers.trimEnd() + '\n\n' + triggersBlock + '\n'
}

/**
 * Generate a wrangler.toml cron trigger comment block for documentation.
 */
export function generateTriggersComment(schedules: string[]): string {
  if (schedules.length === 0) return '# No plugin cron schedules declared.'
  return [
    '# Cron triggers — generated by scripts/generate-cron-triggers.ts',
    '# Source: plugin crons[] declarations. Do not edit manually.',
    '[triggers]',
    `crons = [${schedules.map((s) => `"${s}"`).join(', ')}]`,
  ].join('\n')
}
