/**
 * Plugin Registry - AUTO-GENERATED
 *
 * Generated by: packages/scripts/generate-plugin-registry.mjs
 * Generated at: 2026-04-10T16:48:02.805Z
 * Source: All manifest.json files in src/plugins/
 *
 * DO NOT EDIT MANUALLY - run the generator script instead.
 * To add a new plugin, create a manifest.json in the plugin directory.
 */

export interface PluginRegistryEntry {
  id: string
  codeName: string
  displayName: string
  description: string
  version: string
  author: string
  category: string
  iconEmoji: string
  is_core: boolean
  permissions: string[]
  dependencies: string[]
  defaultSettings: Record<string, any>
  adminMenu: {
    label: string
    icon: string
    path: string
    order: number
  } | null
}

/**
 * All discovered plugins, keyed by plugin ID.
 */
export const PLUGIN_REGISTRY: Record<string, PluginRegistryEntry> = {
  'ai-search': {
    "id": "ai-search",
    "codeName": "ai-search-plugin",
    "displayName": "AI Search",
    "description": "Advanced search with Cloudflare AI Search. Full-text search, semantic search, and advanced filtering across all content collections.",
    "version": "1.0.0",
    "author": "SonicJS",
    "category": "content",
    "iconEmoji": "🔍",
    "is_core": true,
    "permissions": [
      "settings:write",
      "admin:access",
      "content:read"
    ],
    "dependencies": [],
    "defaultSettings": {
      "enabled": true,
      "ai_mode_enabled": true,
      "selected_collections": [],
      "dismissed_collections": [],
      "autocomplete_enabled": true,
      "cache_duration": 1,
      "results_limit": 20,
      "index_media": false
    },
    "adminMenu": {
      "label": "AI Search",
      "icon": "magnifying-glass",
      "path": "/admin/plugins/ai-search",
      "order": 50
    }
  },

  'code-examples-plugin': {
    "id": "code-examples-plugin",
    "codeName": "code-examples-plugin",
    "displayName": "Code Examples",
    "description": "Code snippets and examples library with syntax highlighting and categorization",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "content",
    "iconEmoji": "💻",
    "is_core": false,
    "permissions": [
      "code-examples:manage"
    ],
    "dependencies": [],
    "defaultSettings": {},
    "adminMenu": null
  },

  'core-analytics': {
    "id": "core-analytics",
    "codeName": "core-analytics",
    "displayName": "Analytics & Insights",
    "description": "Core analytics system for tracking page views, user behavior, and content performance. Provides dashboards and reports with real-time metrics",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "seo",
    "iconEmoji": "📊",
    "is_core": true,
    "permissions": [
      "analytics:view",
      "analytics:export"
    ],
    "dependencies": [],
    "defaultSettings": {},
    "adminMenu": {
      "label": "Analytics",
      "icon": "chart-bar",
      "path": "/admin/analytics",
      "order": 50
    }
  },

  'core-auth': {
    "id": "core-auth",
    "codeName": "core-auth",
    "displayName": "Authentication System",
    "description": "Core authentication and user management system with role-based access control, session management, and security features",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "security",
    "iconEmoji": "🔐",
    "is_core": true,
    "permissions": [
      "manage:users",
      "manage:roles",
      "manage:permissions"
    ],
    "dependencies": [],
    "defaultSettings": {
      "requiredFields": {
        "email": {
          "required": true,
          "minLength": 5,
          "label": "Email",
          "type": "email"
        },
        "password": {
          "required": true,
          "minLength": 8,
          "label": "Password",
          "type": "password"
        },
        "username": {
          "required": true,
          "minLength": 3,
          "label": "Username",
          "type": "text"
        },
        "firstName": {
          "required": true,
          "minLength": 1,
          "label": "First Name",
          "type": "text"
        },
        "lastName": {
          "required": true,
          "minLength": 1,
          "label": "Last Name",
          "type": "text"
        }
      },
      "validation": {
        "emailFormat": true,
        "allowDuplicateUsernames": false,
        "passwordRequirements": {
          "requireUppercase": false,
          "requireLowercase": false,
          "requireNumbers": false,
          "requireSpecialChars": false
        }
      },
      "registration": {
        "enabled": true,
        "requireEmailVerification": false,
        "defaultRole": "viewer"
      }
    },
    "adminMenu": null
  },

  'core-cache': {
    "id": "core-cache",
    "codeName": "core-cache",
    "displayName": "Cache System",
    "description": "Three-tiered caching system with in-memory and KV storage. Provides automatic caching for content, users, media, and API responses with configurable TTL and invalidation patterns.",
    "version": "1.0.0-beta.1",
    "author": "SonicJS",
    "category": "system",
    "iconEmoji": "⚡",
    "is_core": true,
    "permissions": [
      "cache.view",
      "cache.clear",
      "cache.invalidate"
    ],
    "dependencies": [],
    "defaultSettings": {
      "enableMemoryCache": true,
      "enableKVCache": true,
      "enableDatabaseCache": true,
      "defaultTTL": 3600
    },
    "adminMenu": null
  },

  'core-media': {
    "id": "core-media",
    "codeName": "core-media",
    "displayName": "Media Manager",
    "description": "Core media upload and management system with support for images, videos, and documents. Includes automatic optimization, thumbnail generation, and cloud storage integration",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "media",
    "iconEmoji": "📸",
    "is_core": true,
    "permissions": [
      "manage:media",
      "upload:files"
    ],
    "dependencies": [],
    "defaultSettings": {},
    "adminMenu": {
      "label": "Media",
      "icon": "image",
      "path": "/admin/media",
      "order": 30
    }
  },

  'database-tools': {
    "id": "database-tools",
    "codeName": "database-tools",
    "displayName": "Database Tools",
    "description": "Database management and administration tools including migrations, backups, and query execution",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "development",
    "iconEmoji": "🗄️",
    "is_core": false,
    "permissions": [
      "database:admin"
    ],
    "dependencies": [],
    "defaultSettings": {
      "enableTruncate": true,
      "enableBackup": true,
      "enableValidation": true,
      "requireConfirmation": true
    },
    "adminMenu": null
  },

  'demo-login-plugin': {
    "id": "demo-login-plugin",
    "codeName": "demo-login-plugin",
    "displayName": "Demo Login",
    "description": "Quick demo login functionality for testing and demonstrations",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "utilities",
    "iconEmoji": "🎯",
    "is_core": false,
    "permissions": [],
    "dependencies": [
      "core-auth"
    ],
    "defaultSettings": {
      "enableNotice": true,
      "demoEmail": "admin@sonicjs.com",
      "demoPassword": "sonicjs!"
    },
    "adminMenu": null
  },

  'design': {
    "id": "design",
    "codeName": "design",
    "displayName": "Design System",
    "description": "Design system management including themes, components, and UI customization. Provides a visual interface for managing design tokens, typography, colors, and component library.",
    "version": "1.0.0-beta.1",
    "author": "SonicJS",
    "category": "utilities",
    "iconEmoji": "🎨",
    "is_core": false,
    "permissions": [
      "design.view",
      "design.edit"
    ],
    "dependencies": [],
    "defaultSettings": {
      "defaultTheme": "light",
      "customCSS": ""
    },
    "adminMenu": {
      "label": "Design",
      "icon": "palette",
      "path": "/admin/design",
      "order": 80
    }
  },

  'easy-mdx': {
    "id": "easy-mdx",
    "codeName": "easy-mdx",
    "displayName": "EasyMDE Markdown Editor",
    "description": "Lightweight markdown editor with live preview. Provides a simple and efficient editor with markdown support for richtext fields.",
    "version": "1.0.0",
    "author": "SonicJS Team",
    "category": "editor",
    "iconEmoji": "📝",
    "is_core": false,
    "permissions": [],
    "dependencies": [],
    "defaultSettings": {
      "defaultHeight": 400,
      "theme": "dark",
      "toolbar": "full",
      "placeholder": "Start writing your content..."
    },
    "adminMenu": null
  },

  'email': {
    "id": "email",
    "codeName": "email",
    "displayName": "Email",
    "description": "Send transactional emails using Resend",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "utilities",
    "iconEmoji": "📧",
    "is_core": false,
    "permissions": [
      "email:manage",
      "email:send",
      "email:view-logs"
    ],
    "dependencies": [],
    "defaultSettings": {
      "apiKey": "",
      "fromEmail": "",
      "fromName": "",
      "replyTo": "",
      "logoUrl": ""
    },
    "adminMenu": {
      "label": "Email",
      "icon": "envelope",
      "path": "/admin/plugins/email/settings",
      "order": 80
    }
  },

  'global-variables': {
    "id": "global-variables",
    "codeName": "global-variables",
    "displayName": "Global Variables",
    "description": "Dynamic content variables that can be referenced as inline tokens in rich text fields. Supports {variable_key} syntax with server-side resolution.",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "content",
    "iconEmoji": "🔤",
    "is_core": false,
    "permissions": [
      "global-variables:manage",
      "global-variables:view"
    ],
    "dependencies": [],
    "defaultSettings": {
      "enableResolution": true,
      "cacheEnabled": true,
      "cacheTTL": 300
    },
    "adminMenu": null
  },

  'hello-world': {
    "id": "hello-world",
    "codeName": "hello-world",
    "displayName": "Hello World",
    "description": "A simple Hello World plugin demonstration",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "utilities",
    "iconEmoji": "👋",
    "is_core": false,
    "permissions": [
      "hello-world:view"
    ],
    "dependencies": [],
    "defaultSettings": {},
    "adminMenu": {
      "label": "Hello World",
      "icon": "hand-raised",
      "path": "/admin/hello-world",
      "order": 90
    }
  },

  'magic-link-auth': {
    "id": "magic-link-auth",
    "codeName": "magic-link-auth",
    "displayName": "Magic Link Authentication",
    "description": "Passwordless authentication via email magic links. Users receive a secure one-time link to sign in without entering a password.",
    "version": "1.0.0",
    "author": "SonicJS Team",
    "category": "security",
    "iconEmoji": "🔗",
    "is_core": false,
    "permissions": [],
    "dependencies": [
      "email"
    ],
    "defaultSettings": {
      "linkExpiryMinutes": 15,
      "rateLimitPerHour": 5,
      "allowNewUsers": true
    },
    "adminMenu": null
  },

  'oauth-providers': {
    "id": "oauth-providers",
    "codeName": "oauth-providers",
    "displayName": "OAuth Providers",
    "description": "OAuth2/OIDC social login with GitHub, Google, and more",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "authentication",
    "iconEmoji": "🔑",
    "is_core": true,
    "permissions": [],
    "dependencies": [],
    "defaultSettings": {
      "providers": {
        "github": {
          "clientId": "",
          "clientSecret": "",
          "enabled": false
        },
        "google": {
          "clientId": "",
          "clientSecret": "",
          "enabled": false
        }
      }
    },
    "adminMenu": null
  },

  'otp-login': {
    "id": "otp-login",
    "codeName": "otp-login",
    "displayName": "OTP Login",
    "description": "Passwordless authentication via email one-time codes",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "security",
    "iconEmoji": "🔢",
    "is_core": false,
    "permissions": [
      "otp:manage",
      "otp:request",
      "otp:verify"
    ],
    "dependencies": [
      "email"
    ],
    "defaultSettings": {
      "codeLength": 6,
      "codeExpiryMinutes": 10,
      "maxAttempts": 3,
      "rateLimitPerHour": 5,
      "allowNewUserRegistration": false
    },
    "adminMenu": {
      "label": "OTP Login",
      "icon": "key",
      "path": "/admin/plugins/otp-login/settings",
      "order": 85
    }
  },

  'quill-editor': {
    "id": "quill-editor",
    "codeName": "quill-editor",
    "displayName": "Quill Rich Text Editor",
    "description": "Quill WYSIWYG editor integration for rich text editing. Lightweight, modern editor with customizable toolbars and dark mode support.",
    "version": "1.0.0",
    "author": "SonicJS Team",
    "category": "editor",
    "iconEmoji": "✍️",
    "is_core": true,
    "permissions": [],
    "dependencies": [],
    "defaultSettings": {
      "version": "2.0.2",
      "defaultHeight": 300,
      "defaultToolbar": "full",
      "theme": "snow"
    },
    "adminMenu": null
  },

  'redirect-management': {
    "id": "redirect-management",
    "codeName": "redirect-management",
    "displayName": "Redirect Management",
    "description": "URL redirect management with exact, partial, and regex matching",
    "version": "1.0.0",
    "author": "ahaas",
    "category": "utilities",
    "iconEmoji": "↪️",
    "is_core": false,
    "permissions": [
      "redirect.manage",
      "redirect.view"
    ],
    "dependencies": [],
    "defaultSettings": {
      "enabled": true,
      "autoOffloadEnabled": false
    },
    "adminMenu": {
      "label": "Redirects",
      "icon": "arrow-right",
      "path": "/admin/redirects",
      "order": 85
    }
  },

  'security-audit': {
    "id": "security-audit",
    "codeName": "security-audit",
    "displayName": "Security Audit",
    "description": "Security event logging, brute-force detection, and analytics dashboard. Monitors login attempts, registrations, lockouts, and suspicious activity.",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "security",
    "iconEmoji": "🛡️",
    "is_core": false,
    "permissions": [
      "security-audit:view",
      "security-audit:manage"
    ],
    "dependencies": [],
    "defaultSettings": {
      "retention": {
        "daysToKeep": 90,
        "maxEvents": 100000,
        "autoPurge": true
      },
      "bruteForce": {
        "enabled": true,
        "maxFailedAttemptsPerIP": 10,
        "maxFailedAttemptsPerEmail": 5,
        "windowMinutes": 15,
        "lockoutDurationMinutes": 30,
        "alertThreshold": 20
      },
      "logging": {
        "logSuccessfulLogins": true,
        "logLogouts": true,
        "logRegistrations": true,
        "logPasswordResets": true,
        "logPermissionDenied": true
      }
    },
    "adminMenu": {
      "label": "Security Audit",
      "icon": "shield-check",
      "path": "/admin/plugins/security-audit",
      "order": 85
    }
  },

  'seed-data': {
    "id": "seed-data",
    "codeName": "seed-data",
    "displayName": "Seed Data Generator",
    "description": "Development tool for generating sample data and testing content. Useful for demos and development environments",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "development",
    "iconEmoji": "🌱",
    "is_core": false,
    "permissions": [
      "seed-data:generate"
    ],
    "dependencies": [],
    "defaultSettings": {
      "userCount": 20,
      "contentCount": 200,
      "defaultPassword": "password123"
    },
    "adminMenu": null
  },

  'stripe': {
    "id": "stripe",
    "codeName": "stripe",
    "displayName": "Stripe Subscriptions",
    "description": "Stripe subscription management with webhook handling, checkout sessions, and subscription gating",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "payments",
    "iconEmoji": "💳",
    "is_core": true,
    "permissions": [
      "stripe:manage",
      "stripe:view"
    ],
    "dependencies": [],
    "defaultSettings": {
      "stripeSecretKey": "",
      "stripeWebhookSecret": "",
      "stripePriceId": "",
      "successUrl": "/admin/dashboard",
      "cancelUrl": "/admin/dashboard"
    },
    "adminMenu": {
      "label": "Stripe",
      "icon": "credit-card",
      "path": "/admin/plugins/stripe",
      "order": 90
    }
  },

  'testimonials-plugin': {
    "id": "testimonials-plugin",
    "codeName": "testimonials-plugin",
    "displayName": "Testimonials",
    "description": "Customer testimonials and reviews management with display widgets and ratings",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "content",
    "iconEmoji": "💬",
    "is_core": false,
    "permissions": [
      "testimonials:manage"
    ],
    "dependencies": [],
    "defaultSettings": {},
    "adminMenu": null
  },

  'tinymce-plugin': {
    "id": "tinymce-plugin",
    "codeName": "tinymce-plugin",
    "displayName": "TinyMCE Rich Text Editor",
    "description": "Powerful WYSIWYG rich text editor for content creation. Provides a full-featured editor with formatting, media embedding, and customizable toolbars for richtext fields.",
    "version": "1.0.0",
    "author": "SonicJS Team",
    "category": "editor",
    "iconEmoji": "📝",
    "is_core": false,
    "permissions": [],
    "dependencies": [],
    "defaultSettings": {
      "apiKey": "no-api-key",
      "defaultHeight": 300,
      "defaultToolbar": "full",
      "skin": "oxide-dark"
    },
    "adminMenu": null
  },

  'turnstile': {
    "id": "turnstile",
    "codeName": "turnstile-plugin",
    "displayName": "Cloudflare Turnstile",
    "description": "CAPTCHA-free bot protection using Cloudflare Turnstile. Provides reusable verification for any form.",
    "version": "1.0.0",
    "author": "SonicJS",
    "category": "security",
    "iconEmoji": "🛡️",
    "is_core": true,
    "permissions": [
      "settings:write",
      "admin:access"
    ],
    "dependencies": [],
    "defaultSettings": {
      "siteKey": "",
      "secretKey": "",
      "theme": "auto",
      "size": "normal",
      "mode": "managed",
      "appearance": "always",
      "preClearanceEnabled": false,
      "preClearanceLevel": "managed",
      "enabled": false
    },
    "adminMenu": {
      "label": "Turnstile",
      "icon": "shield-check",
      "path": "/admin/plugins/turnstile/settings",
      "order": 100
    }
  },

  'user-profiles': {
    "id": "user-profiles",
    "codeName": "user-profiles",
    "displayName": "User Profiles",
    "description": "Configurable custom profile fields for users",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "users",
    "iconEmoji": "👤",
    "is_core": true,
    "permissions": [],
    "dependencies": [],
    "defaultSettings": {},
    "adminMenu": null
  },

  'workflow-plugin': {
    "id": "workflow-plugin",
    "codeName": "workflow-plugin",
    "displayName": "Workflow Engine",
    "description": "Content workflow and approval system with customizable states, transitions, and review processes",
    "version": "1.0.0-beta.1",
    "author": "SonicJS Team",
    "category": "content",
    "iconEmoji": "🔄",
    "is_core": false,
    "permissions": [
      "workflow:manage",
      "workflow:approve"
    ],
    "dependencies": [],
    "defaultSettings": {
      "enableApprovalChains": true,
      "enableScheduling": true,
      "enableAutomation": true,
      "enableNotifications": true
    },
    "adminMenu": null
  }
} as const

/**
 * All plugin IDs.
 */
export const ALL_PLUGIN_IDS = Object.keys(PLUGIN_REGISTRY)

/**
 * Plugins that have their own admin page (have an adminMenu entry).
 */
export const PLUGINS_WITH_ADMIN_PAGES = ALL_PLUGIN_IDS.filter(
  id => PLUGIN_REGISTRY[id]?.adminMenu !== null
)

/**
 * Look up a plugin by its codeName (the `name` field stored in the DB).
 * Falls back to id lookup if no codeName match.
 */
export function findPluginByCodeName(codeName: string): PluginRegistryEntry | undefined {
  return Object.values(PLUGIN_REGISTRY).find(p => p.codeName === codeName)
    || PLUGIN_REGISTRY[codeName]
}

/**
 * Get a plugin by ID.
 */
export function getPlugin(id: string): PluginRegistryEntry | undefined {
  return PLUGIN_REGISTRY[id]
}
