/**
 * Core Plugins Export
 *
 * Exports all core SonicJS plugins
 *
 * NOTE: The list of core plugins is now auto-generated from manifest.json files
 * See: src/plugins/plugin-registry.ts (auto-generated by packages/scripts/generate-plugin-registry.mjs)
 */

export { authPlugin, createAuthPlugin } from './auth'
export { mediaPlugin, createMediaPlugin } from './media'
export { analyticsPlugin, createAnalyticsPlugin } from './analytics'
export { demoLoginPlugin } from './demo-login'
export { workflowPlugin, createWorkflowPlugin } from './workflow-plugin'
export { databaseToolsPlugin } from './database-tools-plugin'
export { helloWorldPlugin, createHelloWorldPlugin } from './hello-world-plugin'
export { quillEditorPlugin, createQuillEditorPlugin } from './quill-editor'
export { lexicalEditorPlugin, createLexicalEditorPlugin } from './lexical-editor'
export { getLexicalStyles, getLexicalImportMap, getLexicalLoaderScript, getLexicalInitScript, renderLexicalField } from './lexical-editor'
export type { LexicalOptions, LexicalToolbarItem } from './lexical-editor'
export { emailPluginV3 as emailPlugin } from './email-plugin'
export { otpLoginPlugin, createOTPLoginPlugin } from './otp-login-plugin'
export { turnstilePlugin } from './turnstile-plugin'
export { TurnstileService, verifyTurnstile, createTurnstileMiddleware } from './turnstile-plugin'
export { aiSearchPlugin } from './ai-search-plugin'
export { AISearchService, IndexManager } from './ai-search-plugin'
export { oauthProvidersPlugin, createOAuthProvidersPlugin } from './oauth-providers'
export { OAuthService, BUILT_IN_PROVIDERS } from './oauth-providers/oauth-service'
export { globalVariablesPlugin, createGlobalVariablesPlugin } from './global-variables-plugin'
export { resolveVariables, resolveVariablesInObject } from './global-variables-plugin'
export { getVariableBlotScript, getVariableTinyMceScript } from './global-variables-plugin'
export { shortcodesPlugin, createShortcodesPlugin } from './shortcodes-plugin'
export { resolveShortcodes, resolveShortcodesInObject, registerShortcodeHandler } from './shortcodes-plugin'
export { getShortcodeBlotScript, getShortcodeTinyMceScript } from './shortcodes-plugin'
export { wrapAdminPage } from './_shared/admin-template'
export { getSharedQuillStyles, getSharedQuillScript, getQuillEnhancerPollerScript } from './_shared/quill-shared'
export { getSharedTinyMceStyles, getTinyMcePluginScript } from './_shared/tinymce-shared'
export { securityAuditPlugin, createSecurityAuditPlugin } from './security-audit-plugin'
export { SecurityAuditService, BruteForceDetector, securityAuditMiddleware } from './security-audit-plugin'
export { userProfilesPlugin, createUserProfilesPlugin, defineUserProfile, getUserProfileConfig } from './user-profiles'
export type { ProfileFieldDefinition, UserProfileConfig } from './user-profiles'
export { stripePlugin, createStripePlugin, SubscriptionService, StripeAPI, requireSubscription } from './stripe-plugin'
export { dashboardPlugin, createDashboardPlugin } from './dashboard-plugin'
export { multiTenantPlugin, createMultiTenantPlugin, TenantService } from './multi-tenant-plugin'
export { versioningPlugin, createVersioningPlugin } from './versioning-plugin'

// Core plugins list - now imported from auto-generated registry
export const CORE_PLUGIN_IDS = [
  'core-auth',
  'core-media',
  'core-analytics',
  'demo-login-plugin',
  'database-tools',
  'hello-world',
  'quill-editor',
  'lexical-editor',
  'email',
  'otp-login',
  'turnstile',
  'ai-search',
  'oauth-providers',
  'global-variables',
  'shortcodes',
  'security-audit',
  'user-profiles',
  'stripe',
  'multi-tenant',
  'versioning'
] as const

export type CorePluginNames = (typeof CORE_PLUGIN_IDS)[number]
